### PR TITLE
Reference docs for 0.27.244707.

### PR DESCRIPTION
**Pull request by kuzminrobin**
**⚠ NOTE**:
This repository only contains automatically generated API documentation, and thus cannot accept pull requests.
If you would like to contribute to the API documentation in this repo, please see the [Quantum Development Kit contribution guide](https://docs.microsoft.com/azure/quantum/contributing-docs#contributing-to-the-api-references) to learn more.

### CODE REVIEW

**Review by Bradben — COMMENTED** [review]
@kuzminrobin - the warnings for the author, date, and description can be ignored. However, we need to sync up and fix the script that generates and configures the files so those fields are correct. Cassandra used to own those - I'm not sure where they are.

**Review by tedhudek — APPROVED** [review]
Hey Robin, I don't have much context here.  Brad on my team is more familiar with this repo.  I mentioned this PR to him and he was going to reach out to you with some minor metadata suggestions.  I had a quick look and didn't see anything egregious so I will simply approve.  Thanks for running the automation here.

**Comment by Bradben** [comment]
@kuzminrobin - if we can fix the metadata creation in the auto-gen process, I'm sure at least 99% of those warnings will disappear. The date, for instance, just needs to include leading zeros. If someone on your team can locate the source files for the process, I can probably figure it out.

**Comment by kuzminrobin** [comment]
> If someone on your team can locate the source files for the process, I can probably figure it out.

@Bradben, Do you mean that you need a list of the file paths to run through an automated tool? If yes then that will likely be all the .md files in the repo (in Linux/WSL a command something like 
`find . -name "*.md"` to get a list of all the file paths;
`find . -name "*.md" -exec <YourTool> \{} \;` to get a list of all the files and execute a tool for every file
).

**Pull request merged**
