### PR TITLE
Restoring index.md for the libraries

### PR DESCRIPTION
**Pull request by geduardo**
**⚠ NOTE**:
This repository only contains automatically generated API documentation, and thus cannot accept pull requests.
If you would like to contribute to the API documentation in this repo, please see the [Quantum Development Kit contribution guide](https://docs.microsoft.com/azure/quantum/contributing-docs#contributing-to-the-api-references) to learn more.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@geduardo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@geduardo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Bradben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@geduardo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
